spring:
  datasource:
    dynamic:
      #configClz: org.jangod.iweb.mapp.config.DataSourceConfig
      enabled: true
      primary: master
      strict: true
      datasource:
        master:
          driverClassName: org.h2.Driver
          url: jdbc:h2:mem:h2temp
        demo:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://203.175.139.40:3306/dv_db_demo?useUnicode=true&characterEncoding=utf-8
          username: demo
          password: '123456a?'