dubbo:
  application:
    name: ${app.code}
    logger: slf4j
  protocol:
    port: 10121
  registry:
    group: ${app.group}
    address: 203.175.130.170:2181
    protocol: zookeeper
    timeout: 60000