#app:
#  l1ClassName: org.jangod.iweb.plugin.cache.redis.RedisCacheProvider
#  redis:
#    host: 203.175.130.170
#    port: 6379
#    database: 9
#    password: ''
#    minIdle: 5
#    maxTotal: 20
#    maxIdle: 10
#    maxWaitMillis: 10000