server:
  port: {{backendPort}}
  servlet:
    context-path:
app:
  code: ${spring.application.name}
  cloudToken: 773252055002251265
  group: csp170
  registry-group: csp170
spring:
  application:
    name: {{name}}-PLUGIN-RUNNER
  profiles:
    active: cache,dubbo,plugin,db
  datasource:
    initialSize: 2
    minIdle: 2
    maxActive: 20
    maxWait: 60000
    filters: stat,wall,slf4j
    connectionProperties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
mybatis-plus:
  config-locations: classpath*:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mappers/**/*.xml
  configuration:
    log-impl: org.jangod.iweb.logging.Slf4jImpl #开启sql日志
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true